### ISSUE TITLE
Courses seconds spent metric no results

### ISSUE THREAD

**Issue by qunabu** [EscolaLMS/Reports#11]
seems like seeder is missing here

**Comment by pa-cholek** [comment]
There isn't really anything to seed here... unless you want some historical report data to be seeded?

**Comment by pa-cholek** [comment]
And `seconds spent` probably should be seeded in ProgressSeeder in Courses if it is not seeded already

**Comment by qunabu** [comment]
> And `seconds spent` probably should be seeded in ProgressSeeder in Courses if it is not seeded already

exactly 👍
