### ISSUE TITLE
add swagger to gh-pages

### ISSUE THREAD

**Issue by qunabu** [EscolaLMS/Reports#2]

**Comment by qunabu** [comment]
![image](https://user-images.githubusercontent.com/214608/133069197-5c6e0bcd-6204-45ce-8481-024fc15e318c.png)
showing tags :( https://escolalms.github.io/Reports/

**Comment by pa-cholek** [comment]
I have no idea how to do this, what even are gh-pages

**Comment by qunabu** [comment]
Github action https://github.com/EscolaLMS/Reports/blob/main/.github/workflows/swagger.yml 
that creates a swagger page for each package on Github Pages 
here should be link to swagger for Reports endpoint but is for Tags :( https://escolalms.github.io/Reports/
